In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Pytorch fundamentals:


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


# 1- Tensors

In [4]:
#SCALAR
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as Python int
scalar.item()

7

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim # dimension is the number of square brackets!

1

In [9]:
vector.shape # 2 elements

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
#anytime you code data into numbers its tensor dtype

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape #total of el =  2*2 or 2*3

torch.Size([2, 2])

In [14]:
MATRIX[1]

tensor([ 9, 10])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors
Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data`

In [18]:
#Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9965, 0.3000, 0.2655, 0.3352],
        [0.6827, 0.1763, 0.9801, 0.2933],
        [0.1438, 0.0936, 0.8668, 0.8644]])

In [19]:
random_tensor.ndim

2

In [20]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height, width, color channels (red,green.blue)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# ZEROS AND ONES

In [21]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# CREATING a RANGE OF TENSORS AND TENSOR- LIKE

In [24]:
# use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#Creating tensors  **** SAME SHAPE ****
ten_zeros = torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#TENSOR DATATYPES
Most errors are coming from this
* how to change dtypes and more

In [26]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #more precision more bit : float64
                               device=None, #what device is your tensor on
                               requires_grad = False) #calculate gradients or not

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
# either change dtype = float16
# or this:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
# What happens if you try to multiple different two dtypes? YOU CAN!!
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3,6,9],dtype= torch.long)
int_32_tensor.dtype

torch.int64

## Getting information from tensors
1. Tensors are not dtype - check `tensor.dtype`
2. Tensors are not right shape - check `tensor.shape`
3. Tensors are not on the right device - check `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4078, 0.9864, 0.9093, 0.0586],
        [0.6266, 0.9946, 0.5443, 0.7479],
        [0.4650, 0.4514, 0.6617, 0.8392]])

In [32]:
# Find out details about some tensor
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: { some_tensor.shape}')
print(f'What device tensor is on: {some_tensor.device}') #default is cpu

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
What device tensor is on: cpu


# MANIPULATING TENSORS ( TENSOR OPERATIONS )

In [33]:
# ADDITION etc:
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

## MATRIX MULTIPLICATION
* element wise
* dot product

In [34]:
# element wise
print(tensor,'*',tensor)
tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [35]:
# matrix multiplication
torch.matmul(tensor,tensor)


tensor(14)

In [36]:
# by hand
(1 * 1) + (2*2) + (3*3)

14

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 898 µs, sys: 0 ns, total: 898 µs
Wall time: 1.12 ms


In [38]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 735 µs, sys: 0 ns, total: 735 µs
Wall time: 1 ms


tensor(14)

##There are two main rules that performing matrix multiplication needs to satisfy:
1- the **inner dimensions** must match:
* `(3,2) @ (3,2)` this won't work
* `(2,3) @ (3,2)` this will work
note: basic matrix mult. rules

2- resulting matrix has the shape of the **outer dimensions**

In [39]:
result = torch.matmul(torch.rand(2,3),torch.rand(3,2))
result.shape

torch.Size([2, 2])

# Most common errors in deep learning is shape errors

In [40]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# matmul = mm
#torch.mm(tensor_A, tensor_B)

In [41]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

## To fix our tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.
## A **transpose** switches the rows with columns.

In [42]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [44]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# FINDING THE MIN, MAX, MEAN, SUM
# TENSOR AGGREGATION

In [45]:
# Create a tensor:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [47]:
# Find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean
# torch.mean(x) ## mean(): could not infer output dtype.
              ## Input dtype must be either a floating point or complex dtype.
              ## Got: Long

In [49]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [50]:
 # Find the sum
 torch.sum(x)

tensor(450)

# Finding the positional min and max

In [51]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.argmin()

tensor(0)

In [53]:
x.argmax()

tensor(9)

# RESHAPING, VIEWING AND STACKING TENSORS

In [54]:
# create a torch
x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
 # add an extra dimention by reshaping:
 x_reshaped = x.reshape(9,1) #or (1,9)
 x_reshaped , x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:
# Change the view
# z shares the same memory with x:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
#changing z changes x ( because a view of a tensor shares the same memory as the original input)
z[:,0] = 5 # first column to be 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
# Stack tensors on top
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [59]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [60]:
 # Squeeze : Removes all single dimensions from a target tensor
 x = torch.zeros(2,1,2,1,2)
 x.size()

torch.Size([2, 1, 2, 1, 2])

In [61]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [62]:
y_unsqueezed = torch.unsqueeze(y, dim = 0)
y_unsqueezed.size()

torch.Size([1, 2, 2, 2])

In [63]:
# PERMUTE : rearragne dimension placements
torch.permute(y_unsqueezed,(2,3,0,1)).size()

torch.Size([2, 2, 1, 2])

# You will use permute in mostly image data

In [64]:
x_image = torch.rand(size=(224,224,3)) #[height,width,color_channels(r,b,g)]

#permute the x_image

x_permuted = x_image.permute(2,0,1)
x_permuted.size()

torch.Size([3, 224, 224])

# INDEXING

In [65]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [66]:
# indexing
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
x[0][0]

tensor([1, 2, 3])

In [68]:
x[0][0][1]

tensor(2)

In [69]:
# you can use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [70]:
#get all the values of 0th and 1st dimensions but only index 1 of second dimension
x[: ,: , 1]

tensor([[2, 5, 8]])

In [71]:
#get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [72]:
x[:,:,2]

tensor([[3, 6, 9]])

# NUMPY

In [3]:
import numpy as np
import torch

In [6]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #default dtype float32
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

# REPRODUCIBILITY
(trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ... `

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.



In [7]:
import torch

#create two random tensors

random_tensor_A = torch.rand(3,4)

random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6479, 0.9997, 0.8547, 0.1829],
        [0.0613, 0.6694, 0.2728, 0.8579],
        [0.7524, 0.6301, 0.6766, 0.4708]])
tensor([[0.3971, 0.9633, 0.7880, 0.3909],
        [0.9074, 0.0911, 0.2520, 0.8122],
        [0.0379, 0.0551, 0.2379, 0.4127]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [8]:
# Lets make some random but reproducible tensors

import torch

#set the random seed

random_seed = 42

torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

Getting a GPU: </p>

1- google colab - can upgrade </p>
2- use your own </p>
3- use cloud computing - GCP, AWS, Azure </p>
For 2,3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to Pytorch setup doc.

In [13]:
# Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

False

In [14]:
# Setup device agnostic code

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [15]:
#count number of devices
torch.cuda.device_count()

0